version: 2

sources:
  - name: jaffle_shop
    database: caramel-brook-342204
    schema: dbt_dataset

    tables:
      - name: jaffle_shop_customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: jaffle_shop_orders
        columns:
          - name: id
            tests:
              - unique
              - not_null